default_language_version:
  python: 'python3.6'
fail_fast: true
repos:

  - repo: 'https://github.com/ambv/black'
    rev: 'stable'
    hooks:
      - id: 'black'

  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: 'v2.1.0'
    hooks:
      - id: 'check-added-large-files'
      - id: 'check-ast'
      - id: 'check-byte-order-marker'
      - id: 'check-docstring-first'
      - id: 'check-executables-have-shebangs'
      - id: 'check-json'
      - id: 'check-symlinks'
      - id: 'check-merge-conflict'
      - id: 'check-vcs-permalinks'
      - id: 'check-xml'
      - id: 'check-yaml'
      - id: 'debug-statements'
      - id: 'end-of-file-fixer'
        exclude: '.bumpversion.cfg'
      - id: 'name-tests-test'
      - id: 'trailing-whitespace'

  - repo: 'git@github.com:Yelp/detect-secrets'
    rev: 'v0.11.4'
    hooks:
      - id: 'detect-secrets'
        args: ['--baseline', '.secrets.baseline']
        exclude: 'tests/*|poetry.lock'

  - repo: 'https://github.com/pre-commit/pygrep-hooks'
    rev: 'v1.2.0'
    hooks:
      - id: 'python-use-type-annotations'
      - id: 'rst-backticks'
      - id: 'python-no-log-warn'

  - repo: 'https://github.com/asottile/reorder_python_imports'
    rev: 'v1.3.5'
    hooks:
      - id: 'reorder-python-imports'
        args: ['--py3-plus']

  - repo: 'local'
    hooks:
      - id: mypy
        name: Check mypy static types match
        entry: mypy gst
        pass_filenames: false
        language: system
        types: [python]
